# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, unique=True, verbose_name='categoria')),
            ],
            options={
                'verbose_name_plural': 'categorias',
                'verbose_name': 'categoria',
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.CharField(max_length=100, verbose_name='filme')),
                ('raised', models.DecimalField(decimal_places=3, max_digits=4, verbose_name='arrecadou')),
                ('liked', models.BooleanField(default=True, verbose_name='gostou')),
                ('release', models.DateTimeField(verbose_name='lançamento')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_category', to='core.Category', verbose_name='categoria')),
            ],
            options={
                'verbose_name_plural': 'filmes',
                'verbose_name': 'filme',
                'ordering': ['-release'],
            },
        ),
        migrations.AlterModelOptions(
            name='distributor',
            options={'ordering': ['distributor'], 'verbose_name': 'distribuidor', 'verbose_name_plural': 'distribuidores'},
        ),
        migrations.AddField(
            model_name='movie',
            name='distributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_distributor', to='core.Distributor', verbose_name='distribuidor'),
        ),
    ]
